# ##################################################################################################
#  The MIT License (MIT)
#  Copyright (c) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software
#  and associated documentation files (the "Software"), to deal in the Software without restriction,
#  including without limitation the rights to use, copy, modify, merge, publish, distribute,
#  sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all copies or
#  substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ##################################################################################################

SUBDIRS := hbm_bandwidth traffic_producer
SUBTARGET ?= all

.PHONY: all clean rebuild $(SUBDIRS) build-% clean-% rebuild-%

all: check-smbus-ip $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@ $(SUBTARGET)

clean:
	@for d in $(SUBDIRS); do \
		$(MAKE) -C $$d clean || exit $$?; \
	done

rebuild: clean all

build-%:
	$(MAKE) -C $* $(SUBTARGET)

clean-%:
	$(MAKE) -C $* clean

rebuild-%:
	$(MAKE) -C $* clean
	$(MAKE) -C $* $(SUBTARGET)

check-smbus-ip:
	@if [ -z "$(wildcard smbus*)" ]; then \
		echo "=======================================================================" >&2; \
		echo "ERROR: SMBus IP (xilinx.com:ip:smbus:1.1) not found in linker/slashkit/resources/base/iprepo/." >&2; \
		echo "Download it from https://www.xilinx.com/member/v80.html and place the IP" >&2; \
		echo "directory into linker/slashkit/resources/base/iprepo/ before building." >&2; \
		echo "See docs/tutorials/admin/platform-setup.rst for details." >&2; \
		echo "=======================================================================" >&2; \
		exit 1; \
	fi
