# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

nl_regs = {
    "mac_address": {'offset': 0x0010, 'size': 8, 'type': 'rw'},
    "ip_address": {'offset': 0x0018, 'size': 4, 'type': 'rw'},
    "gateway": {'offset': 0x001C, 'size': 4, 'type': 'rw'},
    "ip_mask": {'offset': 0x0020, 'size': 4, 'type': 'rw'},
    "eth_in_cycles": {'offset': 0x0400, 'size': 8, 'type': 'ro'},
    "eth_in_bytes": {'offset': 0x0408, 'size': 8, 'type': 'ro'},
    "eth_in_packets": {'offset': 0x0410, 'size': 8, 'type': 'ro'},
    "pkth_in_cycles": {'offset': 0x0418, 'size': 8, 'type': 'ro'},
    "pkth_in_bytes": {'offset': 0x0420, 'size': 8, 'type': 'ro'},
    "pkth_in_packets": {'offset': 0x0428, 'size': 8, 'type': 'ro'},
    "arp_in_cycles": {'offset': 0x0430, 'size': 8, 'type': 'ro'},
    "arp_in_bytes": {'offset': 0x0438, 'size': 8, 'type': 'ro'},
    "arp_in_packets": {'offset': 0x0440, 'size': 8, 'type': 'ro'},
    "arp_out_cycles": {'offset': 0x0448, 'size': 8, 'type': 'ro'},
    "arp_out_bytes": {'offset': 0x0450, 'size': 8, 'type': 'ro'},
    "arp_out_packets": {'offset': 0x0458, 'size': 8, 'type': 'ro'},
    "icmp_in_cycles": {'offset': 0x0460, 'size': 8, 'type': 'ro'},
    "icmp_in_bytes": {'offset': 0x0468, 'size': 8, 'type': 'ro'},
    "icmp_in_packets": {'offset': 0x0470, 'size': 8, 'type': 'ro'},
    "icmp_out_cycles": {'offset': 0x0478, 'size': 8, 'type': 'ro'},
    "icmp_out_bytes": {'offset': 0x0480, 'size': 8, 'type': 'ro'},
    "icmp_out_packets": {'offset': 0x0488, 'size': 8, 'type': 'ro'},
    "ethhi_out_cycles": {'offset': 0x0490, 'size': 8, 'type': 'ro'},
    "ethhi_out_bytes": {'offset': 0x0498, 'size': 8, 'type': 'ro'},
    "ethhi_out_packets": {'offset': 0x04A0, 'size': 8, 'type': 'ro'},
    "eth_out_cycles": {'offset': 0x04A8, 'size': 8, 'type': 'ro'},
    "eth_out_bytes": {'offset': 0x04B0, 'size': 8, 'type': 'ro'},
    "eth_out_packets": {'offset': 0x04B8, 'size': 8, 'type': 'ro'},
    "udp_in_cycles": {'offset': 0x04C0, 'size': 8, 'type': 'ro'},
    "udp_in_bytes": {'offset': 0x04C8, 'size': 8, 'type': 'ro'},
    "udp_in_packets": {'offset': 0x04D0, 'size': 8, 'type': 'ro'},
    "app_out_cycles": {'offset': 0x04D8, 'size': 8, 'type': 'ro'},
    "app_out_bytes": {'offset': 0x04E0, 'size': 8, 'type': 'ro'},
    "app_out_packets": {'offset': 0x04E8, 'size': 8, 'type': 'ro'},
    "udp_out_cycles": {'offset': 0x04F0, 'size': 8, 'type': 'ro'},
    "udp_out_bytes": {'offset': 0x04F8, 'size': 8, 'type': 'ro'},
    "udp_out_packets": {'offset': 0x0500, 'size': 8, 'type': 'ro'},
    "app_in_cycles": {'offset': 0x0508, 'size': 8, 'type': 'ro'},
    "app_in_bytes": {'offset': 0x0510, 'size': 8, 'type': 'ro'},
    "app_in_packets": {'offset': 0x0518, 'size': 8, 'type': 'ro'},
    "debug_reset_counters": {'offset': 0x05F0, 'size': 4, 'type': 'rw'},
    "frequency": {'offset': 0x05F4, 'size': 4, 'type': 'ro'},
    "probes_ports": {'offset': 0x05F8, 'size': 4, 'type': 'ro'},
    "probes_mode": {'offset': 0x05FC, 'size': 4, 'type': 'ro'},
    "udp_number_sockets": {'offset': 0x0810, 'size': 4, 'type': 'ro'},
    "udp_theirIP_offset": {'offset': 0x0820, 'size': 4, 'type': 'rw'},
    "udp_theirPort_offset": {'offset': 0x08A0, 'size': 4, 'type': 'rw'},
    "udp_myPort_offset": {'offset': 0x0920, 'size': 4, 'type': 'rw'},
    "udp_valid_offset": {'offset': 0x09A0, 'size': 4, 'type': 'rw'},
    "arp_discovery": {'offset': 0x1010, 'size': 4, 'type': 'rw'},
    "arp_valid_offset": {'offset': 0x1100, 'size': 4, 'type': 'rw'},
    "arp_ip_addr_offset": {'offset': 0x1400, 'size': 4, 'type': 'rw'},
    "arp_mac_addr_offset": {'offset': 0x1800, 'size': 4, 'type': 'rw'},
}