import importlib.resources as resources
import logging
import os
import re
import shlex
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from subprocess import check_call
from typing import Literal, override

from setuptools import Command, setup
from setuptools.command.build import build

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s:%(funcName)s: %(message)s",
)


logger = logging.getLogger(__name__)

AVED_DESIGN_NAME = "amd_v80_gen5x8_25.1"

# Host toolchain flags injected by dpkg-buildpackage (e.g. -mno-omit-leaf-frame-pointer,
# -fcf-protection, -fstack-clash-protection) are not understood by the arm-xilinx-eabi
# cross-compiler used for the AVED AMC firmware. Strip them before shelling out.
_CROSS_BUILD_ENV_BLOCKLIST = (
    "CFLAGS",
    "CXXFLAGS",
    "CPPFLAGS",
    "LDFLAGS",
    "FFLAGS",
    "FCFLAGS",
    "OBJCFLAGS",
    "OBJCXXFLAGS",
    "GCJFLAGS",
    "ASFLAGS",
)


def _clean_cross_build_env() -> dict[str, str]:
    env = {k: v for k, v in os.environ.items() if k not in _CROSS_BUILD_ENV_BLOCKLIST}
    return {k: v for k, v in env.items() if not k.startswith("DEB_")}


def _copy_file(src_file: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    try:
        shutil.copy2(src_file, destination / src_file.name)
    except shutil.SameFileError:
        logger.info(
            "Skipping copy because source and destination are the same file: %s",
            src_file,
        )


def _copy_tree(src_dir: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src_dir, destination / src_dir.name, dirs_exist_ok=True)


def _ensure_boot_device_pcie_in_bif(bif_path: Path) -> None:
    if not bif_path.exists():
        raise FileNotFoundError(f"Expected BIF file not found: {bif_path}")

    lines = bif_path.read_text().splitlines()
    if any(line.strip() == "boot_device { pcie }" for line in lines):
        return

    # Find id=0x2
    pattern = re.compile(r"^(\s*)id\s*=\s*0x2\s*$")
    for idx, line in enumerate(lines):
        match = pattern.match(line)
        if match:
            lines.insert(idx + 1, f"{match.group(1)}boot_device {{ pcie }}")
            bif_path.write_text("\n".join(lines) + "\n")
            return

    raise ValueError(f"Could not find 'id = 0x2' in BIF file: {bif_path}")


def _generate_top_wrapper_pdi_with_bootgen(impl_dir: Path) -> Path:
    bif_path = impl_dir / "top_wrapper.bif"
    output_pdi = impl_dir / "top_wrapper.pdi"

    _ensure_boot_device_pcie_in_bif(bif_path)
    logger.info("Running bootgen in %s to generate %s", impl_dir, output_pdi.name)
    subprocess.run(
        [
            "bootgen",
            "-arch",
            "versal",
            "-image",
            bif_path.name,
            "-w",
            "-o",
            output_pdi.name,
        ],
        cwd=str(impl_dir),
        check=True,
    )

    if not output_pdi.exists():
        raise FileNotFoundError(f"Expected bootgen output not found: {output_pdi}")
    return output_pdi


class BuildAVED:
    def __init__(
        self,
        aved_repo: str,
        aved_ref: str,
        build_dir: Path,
        top_wrapper_pdi: Path,
    ):
        self.aved_repo = aved_repo
        self.aved_ref = aved_ref
        self.top_wrapper_pdi = top_wrapper_pdi

        self._aved = build_dir / "AVED"
        self._aved_hw = self._aved / "hw" / AVED_DESIGN_NAME

    def __call__(self):
        self.clone()
        self.prepare()

        # Run the AVED build script
        logger.info("Running AVED build script in %s", self._aved_hw)
        subprocess.run(
            ["bash", "build_all.sh"],
            cwd=self._aved_hw,
            env=_clean_cross_build_env(),
            check=True,
        )

        # Collect the generated PDI
        aved_pdi = self._aved_hw / f"{AVED_DESIGN_NAME}.pdi"
        if not aved_pdi.exists():
            raise FileNotFoundError(f"Expected AVED output not found: {aved_pdi}")
        logger.info("AVED fallback complete. Generated %s", aved_pdi)

        return aved_pdi

    def clone(self):
        if (self._aved / ".git").exists():
            logger.warning(
                "AVED already cloned. Please remove %s to force a fresh clone.",
                self._aved,
            )
            return

        check_call(
            [
                "git",
                "clone",
                "--recurse-submodules",
                "-b",
                self.aved_ref,
                self.aved_repo,
                self._aved,
            ]
        )

    def prepare(self):
        # Inject the top wrapper PDI generated by Vivado into the AVED hardware
        # directory to be used as the base for the AVED build.
        _copy_file(self.top_wrapper_pdi, self._aved_hw / "build")

        # Patch AVED
        files_to_copy = [
            ("build_all.sh", self._aved_hw),
            ("profile_hal.h", self._aved / "fw/AMC/src/profiles/v80"),
            ("pdi_combine.bif", self._aved_hw / "fpt"),
            (f"{AVED_DESIGN_NAME}.xsa", self._aved_hw / "build"),
        ]

        for file_name, target_dir in files_to_copy:
            with resources.path("slashkit.resources.aved", file_name) as in_path:
                _copy_file(in_path, target_dir)


class BuildFPGA:
    def __init__(
        self,
        vivado_bin: Path,
        project_name: str,
        build_dir: Path,
        jobs: int = 14,
    ):
        self.vivado_bin = vivado_bin
        self.project_name = project_name
        self.build_dir = build_dir
        self.jobs = jobs

        self._slash = self.build_dir / "slash"
        self._proj = self.build_dir / f"{self.project_name}.xpr.zip"
        self._impl = self.build_dir / f"{self.project_name}.impl.zip"

    def __call__(self):
        self.build()

        self._reinstate_project(self._impl)
        assert self._slash.is_dir()

        regenerated_top_wrapper_pdi = _generate_top_wrapper_pdi_with_bootgen(
            self._slash / "slash.runs/impl_1"
        )

        return self._slash, regenerated_top_wrapper_pdi

    def build(self):
        if self._impl.exists():
            return

        if not self._proj.exists():
            self.create_project()

            if not self._proj.exists():
                raise FileNotFoundError(f"Project archive not found: {self._proj}")

        if not self._impl.exists():
            self.build_project()

            if not self._impl.exists():
                raise FileNotFoundError(f"Project archive not found: {self._impl}")

    def build_iprepo(self) -> Path:
        _iprepo = Path("iprepo").resolve()
        _build_dir = self.build_dir / "iprepo"

        # Check for SMBus IP core in the IP repository before continuing
        if not list(_iprepo.rglob("smbus*/component.xml")):
            raise FileNotFoundError(f"Expected SMBus IP core not found in {_iprepo}.")

        _copy_tree(_iprepo, self.build_dir)
        assert _build_dir.is_dir()

        # Build the HLS IP cores
        check_call(["make", f"-j{self.jobs}"], cwd=_build_dir)

        # Extract all built IP cores into the IP repository for Vivado to use
        for subdir in _build_dir.iterdir():
            if not subdir.is_dir():
                continue

            src = subdir / f"ip/{subdir.name}.zip"
            if not src.exists():
                continue

            dst = (_iprepo / subdir.name).resolve()
            check_call(["unzip", "-o", src, "-d", dst])

        return _iprepo

    def create_project(self):
        iprepo = self.build_iprepo()
        if self._slash.exists():
            shutil.rmtree(self._slash)

        self._slash.mkdir(parents=True, exist_ok=False)
        self._launch_vivado(action="create", iprepo=iprepo)

    def build_project(self):
        self._reinstate_project(self._proj)
        assert self._slash.is_dir()
        self._launch_vivado(action="build")

    def _reinstate_project(self, archive: Path):
        assert zipfile.is_zipfile(archive), f"Expected a zip archive: {archive}"

        if self._slash.exists():
            shutil.rmtree(self._slash)

        check_call(["unzip", archive, "-d", self._slash.parent])

    def _launch_vivado(
        self,
        iprepo: Path | None = None,
        action: Literal["create", "build", "all"] = "all",
    ) -> None:
        with resources.path(
            "slashkit.resources.base.scripts", "create_project.tcl"
        ) as tcl_path:
            if not tcl_path.exists():
                raise FileNotFoundError(f"create_project.tcl not found: {tcl_path}")

            cmd = [
                self.vivado_bin,
                "-mode",
                "batch",
                "-source",
                tcl_path,
                "-tclargs",
                self.project_name,
            ]

            if iprepo and iprepo.exists():
                cmd.append(iprepo)

            if action:
                cmd.append(action)

            if self.jobs:
                cmd.append(str(self.jobs))

            cmd = [str(arg) for arg in cmd]
            logger.info(shlex.join(cmd))
            check_call(cmd, cwd=self._slash)

        # Move any generated project archives to the build directory
        for archive in self._slash.glob("*.zip"):
            logger.info(f"Found archive: {archive}")
            archive.rename(self.build_dir / archive.name)


class install_static(Command):
    description = """
    Purpose:
      The 'install' subcommand builds the static shell required for
      hardware builds. This is a one-time setup operation that creates base images
      used by the 'link' subcommand when targeting hardware (-p hw).

    When to Use:
      - During initial installation and/or packaging of slashkit
      - When the static shell definition needs to be regenerated

      Most users will NOT need to run this command regularly. It is only required
      during linker installation/setup.

    What It Does:
      1. Builds the static shell base images from the resource directory
      2. Generates necessary Vivado synthesis artifacts
      3. Creates reusable partial designs for hardware linking

      WARNING: This operation involves full Vivado synthesis and implementation,
      which takes significant time (multiple hours depending on the system).

    Build Artifacts:
      The build directory (--build-dir) will contain Vivado projects, checkpoints,
      and logs. This directory can be removed after successful installation.
    """
    user_options = [
        (
            "vivado=",
            None,
            "Vivado binary to use for linking. If not given, it will be derived from PATH.",
        ),
        (
            "build-dir=",
            None,
            "The build directory for the installer. Default: ./install.prj",
        ),
        (
            "aved-repo=",
            None,
            "The AVED git repository to check out. Default: https://github.com/Xilinx/AVED.git",
        ),
        (
            "aved-ref=",
            None,
            "The AVED git ref to check out. Default: amd_v80_gen5x8_25.1_xbtest_20251113",
        ),
        (
            "out-dir=",
            None,
            "The resource directory to install the artifacts to.",
        ),
        (
            "jobs=",
            None,
            "The number of parallel jobs to use for building.",
        ),
    ]

    @override
    def initialize_options(self):
        self.vivado = shutil.which("vivado")
        self.project_name = "slash_install"
        self.build_dir = "install.prj"
        self.ip_repository = None
        self.aved_repo = "https://github.com/Xilinx/AVED.git"
        self.aved_ref = "amd_v80_gen5x8_25.1_xbtest_20251113"
        self.out_dir = "slashkit/resources"
        self.jobs = max((os.cpu_count() or 0) // 2, 1)

    @override
    def finalize_options(self):
        self.vivado_bin = self.vivado and Path(self.vivado).expanduser().resolve()
        if not self.vivado_bin or not self.vivado_bin.exists():
            raise RuntimeError(
                "Vivado binary not found in PATH. Please specify with --vivado."
            )

    @override
    def run(self):
        sys.path.insert(0, str(Path(__file__).parent.resolve()))

        fpga_prj, aved_pdi = self._build()
        self._install(fpga_prj, aved_pdi)

    def _build(self):
        assert self.vivado_bin
        self.build_dir = Path(self.build_dir)
        self.build_dir.mkdir(parents=True, exist_ok=True)

        fpga_prj, regenerated_top_wrapper_pdi = BuildFPGA(
            vivado_bin=Path(self.vivado_bin),
            project_name=self.project_name,
            build_dir=Path(self.build_dir),
            jobs=self.jobs,
        )()

        aved_pdi = BuildAVED(
            aved_repo=self.aved_repo,
            aved_ref=self.aved_ref,
            build_dir=Path(self.build_dir),
            top_wrapper_pdi=regenerated_top_wrapper_pdi,
        )()

        return fpga_prj, aved_pdi

    def _install(self, fpga_prj: Path, aved_pdi: Path):
        static_shell_dir = Path(self.out_dir) / "static_shell"

        # Install IP Repository
        _copy_tree(fpga_prj / "slash.ipdefs/iprepo", Path(self.out_dir) / "base")

        # Install important DCPs and BD sources needed for linking.
        impl_1 = fpga_prj / "slash.runs/impl_1"
        _copy_file(impl_1 / "top_wrapper_routed_bb.dcp", static_shell_dir)
        _copy_file(impl_1 / "static_shell_slash.dcp", static_shell_dir)
        _copy_file(impl_1 / "static_shell_service_layer.dcp", static_shell_dir)

        sources_1 = fpga_prj / "slash.srcs/sources_1"
        _copy_tree(sources_1 / "bd/slash_base", static_shell_dir)
        _copy_tree(sources_1 / "bd/service_layer", static_shell_dir)

        # Install the final AVED PDI into the static shell directory
        _copy_file(aved_pdi, static_shell_dir)

        # Add __init__.py files to make the static shell directory a proper
        # Python package, which allows us to
        def add_init_files(path: Path):
            (path / "__init__.py").touch()
            for sub_path in path.iterdir():
                if not sub_path.is_dir():
                    continue
                add_init_files(sub_path)

        add_init_files(static_shell_dir)


class build_with_static(build):
    sub_commands = [("install_static", None)] + build.sub_commands


setup(
    cmdclass={
        "install_static": install_static,
        "build": build_with_static,
    },
)
