name: Import a PR branch into the repository
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: The pull request ID to import
        required: true
        type: int

jobs:
  import_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          gh pr checkout -b "pr/${{inputs.pr_number}}" ${{inputs.pr_number}}
          git push "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" "pr/${{inputs.pr_number}}"
